package:
    name: eman2
    #version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
    version: 2.2

source:
  git_url: git@github.com:cryoem/eman2.git
  git_tag: anaconda-wip

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
    build:
        - zlib
        - cmake
        - pyopengl
        - numpy
        - ftgl
        - freetype
        - gsl
        - boost
        - fftw
        - hdf5
        - libtiff
        - jpeg
        - libpng
        - python <3
    run:
        - python <3
        - numpy
        - matplotlib
        - boost
        - ipython
        - pyqt
        - qt
        - pyopengl
        - ftgl
        - bsddb
        - readline
        - libtiff
        - jpeg
        - libpng

about:
  home: http://blake.bcm.edu/emanwiki
  license: GPL2
  license_file: LICENSE.txt
  summary: A scientific image processing software suite with a focus on CryoEM and CryoET

extra:
  maintainers:
    - Steve Ludtke
    - James Michael Bell
    - Vernon Williams
