package:
    name: eman2
    version: 2.1.2

source:
  git_url: git@github.com:cryoem/eman2.git
  git_tag: dist

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
    build:
        - zlib
        - cmake
        - numpy ==1.9
        - ftgl
        - freetype
        - gsl
        - boost #>1.57
        - fftw
        - hdf5
        - libtiff
        - jpeg
        - libpng
        - python <3
    run:
        - python <3
        - numpy ==1.9
        - matplotlib
        - boost #>1.57
        - ipython
        - pyqt
        - qt
        - pyopengl
        - ftgl
        - bsddb
        - readline
        - libtiff
        - jpeg
        - libpng

about:
  home: http://blake.bcm.edu/emanwiki
  license: GPL2
  license_file: LICENSE.txt
  summary: A scientific image processing software suite with a focus on CryoEM and CryoET

extra:
  maintainers:
    - Steve Ludtke

